// 006-build-a-laravel-blog-using-vue-and-canvas/resources/js/pages/Welcome.vue
<script setup>

import logotype from '/public/assets/capsules-logotype-red-blue-home.svg';

</script>

<template>

    <div id="capsules" class="w-full min-h-screen flex flex-col font-sans text-primary-black">

        <div class="grow mx-8 lg:mx-auto max-w-screen-lg overflow-auto flex flex-col items-center justify-center text-center">

            <img class="w-24 h-24" v-bind:src="logotype">

            <h1 class="mt-4 text-6xl font-bold select-none header-mode" v-text="'Capsules Codes'" />

        </div>

    </div>

</template>

// resources/js/pages/Welcome.jsx
const Welcome = () =>
{
    const logotype = "/assets/capsules-logotype.svg";

    return (
        <div className="w-screen h-screen flex flex-col items-center justify-center text-center">

            <img className="w-24 h-24" src={ logotype } alt="Capsules Codes Logotype" />

            <h1 className="mt-4 text-6xl font-bold select-none header-mode">Capsules Codes</h1>

        </div>
    );
};


export default Welcome;
